weights: ./weights/yolov4-csp-s-leaky.weights
cfg: ./cfg/yolov4-csp-s-leaky.cfg
data: datasets/obj.yaml
hyp: data/hyp.scratch.yaml
epochs: 3
batch_size: 20
total_batch_size: 20
img_size:
- 448
- 448
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
name: exp
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 0
world_size: 1
project: runs/train
exist_ok: true
global_rank: -1
save_dir: runs\train\exp
